/* ============================================================
   DEMO · content configuration
   ------------------------------------------------------------
   This is the public demo build. Every person, photo and line of
   copy below is fictional. The images are generated by
   tools/make-demo-photos.py and contain no real photography.

   This file is the only one you need to edit. Save, refresh, done.
   Drop images into photos/ and write the filenames below.
   (Missing files are fine, you get a soft placeholder card.)
   ============================================================ */

window.CONTENT = {

  /* ---------- Prelude (loading screen) ---------- */
  site: {
    en: 'A LITTLE UNIVERSE',
    cn: 'Happy 18th birthday\nMia',   // \n becomes a line break
    loading: 'Loading memories...',
    enter: 'ENTER',
    or: 'OR?',
    // the line that appears when you click OR?
    orMsg: 'This is a demo. Everything here is fictional.',
  },

  /* ----------  The three lines at the top of each chapter ----------
     line : the small line of English above
     cn   : the large heading in the middle
     sub  : the small line underneath
     ---------------------------------------------------------------- */
  chapters: {
    candles:  { line: 'PROLOGUE · EIGHTEEN CANDLES' },
    memories: { line: 'CHAPTER ONE · MEMORIES',      cn: 'Stop One',   sub: 'starting the day we met' },
    meals:    { line: 'CHAPTER TWO · EAT WITH YOU',  cn: 'Stop Two',   sub: 'every meal we shared, turn one over' },
    childhood:{ line: 'CHAPTER THREE · LITTLE YOU',  cn: 'Stop Three', sub: 'where the story begins' },
    song:     { line: 'CHAPTER FOUR · OUR SONG',     cn: 'Stop Four',  sub: 'our song' },
    letter:   { line: 'CHAPTER FIVE · LETTER',       cn: 'Stop Five',  sub: 'a letter for you' },
    surprise: { line: 'LAST STOP · ONE MORE THING',  cn: 'Last Stop',  sub: 'one more thing' },
  },

  /* ---------- The birthday person ---------- */
  meta: {
    name: 'Mia',
    fullName: 'Mia',
    age: 18,
    birthday: '2008-12-20',        // date of birth, the big day is worked out from this
    openingTitle: 'Light the candles first',
    openingSubtitle: 'Eighteen of them, one at a time.\nOnce they are all lit, you can go in.',
    openingHint: 'Press and drag across each candle',
    openingSubDone: '',               // if set, replaces the line above once all 18 are lit
    openingDone: 'Eighteen candles, eighteen years of you.',
    heroSub: 'A whole little universe of memories in here',
    enterButton: 'Enter the memory universe',   // the button after all candles are lit
  },

  /* ============================================================
     1. Memory timeline
     ------------------------------------------------------------
     src   : image filename, e.g. 'photos/timeline/01.jpg'
     date  : anything you like, '2019.06', 'summer 2021', 'that one afternoon'
     title : what to call this moment
     text  : a line or two about it (can be left as '')
     Copy a row to add one, delete a row to remove one.
     ============================================================ */
  memories: [
    { src: 'photos/demo/timeline/01.jpg', date: 'Year one · spring', title: 'The day we met',
      text: 'We were standing in the same queue and said maybe four words to each other. Neither of us guessed there would be a story after that.' },
    { src: 'photos/demo/timeline/02.jpg', date: 'Year one · summer', title: 'That long walk',
      text: 'The road was genuinely long, but it never felt that way with someone next to you.' },
    { src: 'photos/demo/timeline/03.jpg', date: 'Year one · autumn', title: 'The first photo of us',
      text: 'Bad light, crooked framing, kept it anyway.' },
    { src: 'photos/demo/timeline/04.jpg', date: 'Year one · winter', title: 'The day it snowed properly',
      text: 'There was only one pair of gloves, so we took one each.' },
    { src: 'photos/demo/timeline/05.jpg', date: 'Year two · spring', title: 'Moving day',
      text: 'More boxes than expected. We finished and ate instant noodles sitting on the floor.' },
    { src: 'photos/demo/timeline/06.jpg', date: 'Year two · summer', title: 'The coast',
      text: 'We swore we would get up for the sunrise. Both of us slept through it.' },
    { src: 'photos/demo/timeline/07.jpg', date: 'Year two · autumn', title: 'The project we survived',
      text: 'The night before the deadline, enough coffee that my hands would not sit still.' },
    { src: 'photos/demo/timeline/08.jpg', date: 'Year two · winter', title: 'New year',
      text: 'Neither of us said anything during the countdown. We just stood there.' },
    { src: 'photos/demo/timeline/09.jpg', date: 'Year three · spring', title: 'First time far away alone',
      text: 'Sent a very long voice note from the airport.' },
    { src: 'photos/demo/timeline/10.jpg', date: 'Year three · summer', title: 'Seeing you again after a long gap',
      text: 'The first thing either of us said was "you cut your hair".' },
    { src: 'photos/demo/timeline/11.jpg', date: 'Year three · autumn', title: 'An ordinary afternoon',
      text: 'We did nothing at all, and I think about it often.' },
    { src: 'photos/demo/timeline/12.jpg', date: 'Today', title: 'Eighteen',
      text: '' },
  ],

  /* ============================================================
     1.5 Quiz gates
     ------------------------------------------------------------
     These sit inside the timeline above. Later memories stay
     locked until the question is answered.
     after   : which memory to sit after (1 = after the first)
     q       : the question
     answers : every acceptable answer, as many as you like
               (case, spacing and punctuation are ignored)
     ok      : what pops up on a correct answer
     tell    : shown if they give up and click "just tell me"
     Set quizzes to [] to turn the whole mechanic off.
     ============================================================ */
  quizzes: [
    {
      after: 0,                       // 0 = before every memory
      q: 'What were we queuing for when we met?',
      answers: ['coffee', 'a coffee', 'the coffee shop', 'coffee shop'],
      ok: 'That coffee shop, yes.',
      tell: 'The coffee shop with the permanent queue.',
    },
    {
      after: 4,
      q: 'How many gloves did we get each in the snow?',
      answers: ['one', '1', 'one each', '1 each'],
      ok: 'One each. Correct.',
      tell: 'One each.',
    },
    {
      after: 12,                      // at the very end of the timeline
      q: 'What should we eat next time?',
      free: true,                     // no right answer, anything passes
      hint: '(no wrong answers here)',
      ok: 'Settled then.',
    },
  ],

  /* ============================================================
     1.8 Meals we shared (flip cards)
     ------------------------------------------------------------
     The front shows only a teaser. Click to flip to the photo.
     teaser : the line on the front (no spoilers, keep it vague)
     name   : the name revealed on the back
     date   : small text on the back (can be empty)
     src    : the image; cards without one still flip to a colour block
     ============================================================ */
  meals: [
    { teaser: 'The first one after we met',    name: 'The noodle place downstairs', date: 'Year one · spring', src: 'photos/demo/meals/01.jpg' },
    { teaser: 'Queued an hour for this',       name: 'That coffee shop',            date: 'Year one · summer', src: 'photos/demo/meals/02.jpg' },
    { teaser: 'Eaten on the floor',            name: 'Instant noodles',             date: 'Year two · spring', src: 'photos/demo/meals/03.jpg' },
    { teaser: 'By the sea, slightly overpriced', name: 'Breakfast with a view',     date: 'Year two · summer', src: 'photos/demo/meals/04.jpg' },
    { teaser: 'The night before the deadline', name: 'Convenience store oden',      date: 'Year two · autumn', src: 'photos/demo/meals/05.jpg' },
    { teaser: 'After the countdown',           name: 'Late night barbecue',         date: 'Year two · winter', src: 'photos/demo/meals/06.jpg' },
    { teaser: 'The reunion meal',              name: 'Hotpot',                      date: 'Year three · summer', src: 'photos/demo/meals/07.jpg' },
    { teaser: 'That ordinary afternoon',       name: 'Two slices of cake',          date: 'Year three · autumn', src: 'photos/demo/meals/08.jpg' },
  ],

  /* ============================================================
     3. Little you · childhood wall
     ------------------------------------------------------------
     Ordered youngest to oldest, do not shuffle them.
     cap is the handwritten line on the polaroid border.
     Leaving it empty also looks good.
     note is the paragraph under the enlarged photo, also optional.
     ============================================================ */
  childhood: {
    items: [
      { src: 'photos/demo/childhood/01.jpg', cap: 'The earliest one',        note: '' },
      { src: 'photos/demo/childhood/02.jpg', cap: 'First time on a stage',   note: '' },
      { src: 'photos/demo/childhood/03.jpg', cap: 'Summer in the courtyard', note: '' },
      { src: 'photos/demo/childhood/04.jpg', cap: 'The day the bike clicked',note: '' },
      { src: 'photos/demo/childhood/05.jpg', cap: 'Uniform still too big',   note: '' },
      { src: 'photos/demo/childhood/06.jpg', cap: 'Almost who you are now',  note: '' },
    ],
  },

  /* ============================================================
     2.5 Background music (plays across the whole site)
     ------------------------------------------------------------
     Leave src empty for no music; the toggle then stays hidden.
     To use it: drop an mp3 in the folder and name it, e.g. 'bgm.mp3'
     Browsers refuse to play audio on page load, so playback starts
     on the ENTER click and then runs uninterrupted to the end.
     ——— The demo ships without audio, to stay clear of licensing. ———
     ============================================================ */
  music: {
    src: '',
    volume: 0.32,
    startAt: 0,        // start at this many seconds in
  },

  /* ============================================================
     3. Our song
     ------------------------------------------------------------
     Leave audio empty and you just get the card (as in this demo).
     To make it play, drop in an mp3 and name it here.
     (Mind the licensing. Listen privately, do not redistribute.)
     ============================================================ */
  song: {
    title: 'Our song',
    artist: 'Demo Artist',
    name: 'Placeholder Track',
    cover: '',
    line: 'A line from the song goes here.',
    note: 'The demo build ships without an audio file.',
    audio: '',
  },

  /* ============================================================
     4. The letter
     ------------------------------------------------------------
     Each string in paragraphs is one paragraph.
     They fade in one after another as you scroll.
     ============================================================ */
  letter: {
    title: 'A letter',
    salutation: 'Dear Mia,',
    paragraphs: [
      'Hope this finds you well.',
      'Happy eighteenth birthday.',
      'This page is placeholder copy. In the real build it is a long letter that fades in a paragraph at a time, and you scroll for a while before you reach the end.',
      'The typography is set for reading rather than scanning: looser line height than the rest of the page, more room between paragraphs, and a lighter weight than the body text, so it reads like paper instead of a web page.',
      'Every font on this site is subset down to the characters the page actually uses, which is why it loads quickly and still renders correctly with no network at all.',
      'To make it yours, edit content.js. That one file, nothing else. Every block in it is commented.',
      'All the best.',
    ],
    // one line per entry
    signature: ['2026.12.20', 'Yours,', 'Demo'],
    ps: '',
  },

  /* ============================================================
     5. The ending
     ============================================================ */
  surprise: {
    hint: 'Close your eyes and make a wish',
    button: 'Blow out the candles',
    title: 'Happy birthday, Mia',
    lines: [
      'May the world be gentle with you,',
      'may there be someone beside you wherever you go,',
      'and may every year after eighteen',
      'leave you liking yourself a little more.',
    ],
    // ---- one last thing, after the candles go out ----
    // set enabled to true to use it
    finale: {
      enabled: true,
      kicker: 'ONE MORE THING',
      title: 'One more thing',
      video: '',                                   // the demo ships without video
      poster: 'photos/demo/finale-poster.jpg',     // cover shown before playback
      link: '',
      linkLabel: 'Take a look',
      note: 'A video or a link can go here.',
    },

    // hidden easter egg: tap the moon in the corner three times
    secret: 'You found it.',
  },
};
